
ö
¨
™§†¥"	mychannelí
ı
Org1MSPÈ-----BEGIN CERTIFICATE-----
MIICtzCCAl2gAwIBAgIUGG2JYL3lLycSBRLn6+unPEf6/XEwCgYIKoZIzj0EAwIw
cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjQwNjI4MTcyMzAwWhcNMjUwNjI4MTcyODAw
WjBgMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExFDASBgNV
BAoTC0h5cGVybGVkZ2VyMQ4wDAYDVQQLEwVhZG1pbjESMBAGA1UEAxMJb3JnMWFk
bWluMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE+9dR7rbe/sqJ/vcRlvwDUR+a
RBjJe8p/nxsXhjc0vlBnCTq1o0gVLPgPkF/Ha/5Hit84GimTgvUflDLhhooc8qOB
5DCB4TAOBgNVHQ8BAf8EBAMCB4AwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUwJn6
IMjIUQsmIAkX1xn8CihJDrQwHwYDVR0jBBgwFoAU1GL4KFmVJqEOjVQlH/mlF/mK
cI0wJAYDVR0RBB0wG4IZUG91cmlhcy1NYWNCb29rLVByby5sb2NhbDBbBggqAwQF
BgcIAQRPeyJhdHRycyI6eyJoZi5BZmZpbGlhdGlvbiI6IiIsImhmLkVucm9sbG1l
bnRJRCI6Im9yZzFhZG1pbiIsImhmLlR5cGUiOiJhZG1pbiJ9fTAKBggqhkjOPQQD
AgNIADBFAiEA6RjGckSCzINASn4bXo8A1obnDeZjYnd6MCd4ZZ8I4PYCIEBS8fEJ
1bQhTHcZn2HGHFutiJ8sf2YQclgWB4WpP5Id
-----END CERTIFICATE-----
ÏË9 {_.?ı€	ä¬¢u\#}˜î5—2Ë

Ö
	mychannel 
Application
Org1MSP’“
Application¬ø
Org1MSP≥Æ
AnchorPeersûë

peer0.org1.example.comã7

peer1.org1.example.comã7

peer1.org1.example.comå7

peer0.org3.example.comå7

peer0.org4.example.comå7Admins›
í
ı
Org1MSPÈ-----BEGIN CERTIFICATE-----
MIICtzCCAl2gAwIBAgIUGG2JYL3lLycSBRLn6+unPEf6/XEwCgYIKoZIzj0EAwIw
cDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMQ8wDQYDVQQH
EwZEdXJoYW0xGTAXBgNVBAoTEG9yZzEuZXhhbXBsZS5jb20xHDAaBgNVBAMTE2Nh
Lm9yZzEuZXhhbXBsZS5jb20wHhcNMjQwNjI4MTcyMzAwWhcNMjUwNjI4MTcyODAw
WjBgMQswCQYDVQQGEwJVUzEXMBUGA1UECBMOTm9ydGggQ2Fyb2xpbmExFDASBgNV
BAoTC0h5cGVybGVkZ2VyMQ4wDAYDVQQLEwVhZG1pbjESMBAGA1UEAxMJb3JnMWFk
bWluMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE+9dR7rbe/sqJ/vcRlvwDUR+a
RBjJe8p/nxsXhjc0vlBnCTq1o0gVLPgPkF/Ha/5Hit84GimTgvUflDLhhooc8qOB
5DCB4TAOBgNVHQ8BAf8EBAMCB4AwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUwJn6
IMjIUQsmIAkX1xn8CihJDrQwHwYDVR0jBBgwFoAU1GL4KFmVJqEOjVQlH/mlF/mK
cI0wJAYDVR0RBB0wG4IZUG91cmlhcy1NYWNCb29rLVByby5sb2NhbDBbBggqAwQF
BgcIAQRPeyJhdHRycyI6eyJoZi5BZmZpbGlhdGlvbiI6IiIsImhmLkVucm9sbG1l
bnRJRCI6Im9yZzFhZG1pbiIsImhmLlR5cGUiOiJhZG1pbiJ9fTAKBggqhkjOPQQD
AgNIADBFAiEA6RjGckSCzINASn4bXo8A1obnDeZjYnd6MCd4ZZ8I4PYCIEBS8fEJ
1bQhTHcZn2HGHFutiJ8sf2YQclgWB4WpP5Id
-----END CERTIFICATE-----
-AæÒ{†Øn9«<wvØŒàËm3'@ÒtF0D ÚUƒ©Å]"ö›ÍZyÊ˙Ç∫xvt ˙>]Yuä EØﬁ®ôÁ≈ö@S§W“e¯K=ñPêﬁU>zè*gáˇœ>F0D ª!x£æz£ıﬂÚûfù∆xΩ≥ux%1ïPN›ì Lﬂ}C“B¡–xuΩn]6ßwÈü	›8tÕWF˙ê*